import Image from 'next/image'
import Navbar from './Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {/* <img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeNrrcuoKYKh6-r0k2ReHqqlm9ef33d-4hyM3iTdED&s' alt='img'></img> */}
        {/* <Image src={require('./laptop1.jpg')} alt='img' width={1300} */}
        {/* height={1000}></Image> */}
        {children}</body>
    </html >
  )
}
